name: Build

on:
  push:
    branches: ["*"]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: Kesin11/actions-timeline@v3.1.0
        with:
          expand-composite-actions: true
          expand-composite-actions-threshold: 10  # 10秒以上のcomposite actionsのみ展開。デフォルトは20秒
      - name: Build
        run: cargo build --release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: tetris-windows
          path: target/release/tetris.exe
